# Numpy 
- Numpy stands for Numerical Python
- Two types of arrays
   - 1-Dimensional Array(Vectors)
   - 2-Dimensional Array(Matrices) 
- To install numpy
  - pip install numpy

In [1]:
#Install the numpy
!pip install numpy

In [2]:
import numpy as np

In [3]:
#Vectors
l1=[1,2,3,4,5]
np.array(l1)

array([1, 2, 3, 4, 5])

In [4]:
#Matrices
l2=[[1,2,3],[4,5,6],[7,8,9]]
np.array(l2)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

#### Numpy array using Built-in methods

#### arange(start=0,stop=n-1,step=1)

In [5]:
np.arange(25)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [6]:
np.arange(5,20)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [7]:
np.arange(1,21,5)

array([ 1,  6, 11, 16])

#### Generate 0's and 1's

In [10]:
np.zeros(3)

array([0., 0., 0.])

In [13]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [14]:
np.ones(3)

array([1., 1., 1.])

In [15]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

#### linspace(start=0,stop=n,num=50)

In [22]:
np.linspace(0,25,5)

array([ 0.  ,  6.25, 12.5 , 18.75, 25.  ])

#### eye()
- Identity matrix
- No.of.Rows = No.of.Columns
- All elements are 0's except diagonal 1's

In [23]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### rand()
- Uniform distribution
- The Value lies b/w 0 and 1

In [26]:
np.random.rand(3)

array([0.57609727, 0.18515554, 0.28720441])

In [27]:
np.random.rand(3,2)

array([[0.18136455, 0.25436594],
       [0.94422666, 0.72332711],
       [0.44959884, 0.050963  ]])

#### randn()
- A Standard Normal Distribution
- Mean=0 and S.D=1

In [28]:
np.random.randn(3)

array([ 0.58443532,  0.63759717, -0.41893148])

In [29]:
np.random.randn(2,3)

array([[-0.41862231,  0.21558319,  0.67695286],
       [ 1.05815839,  0.16754391, -0.27908415]])

#### randint(start,stop,size)

In [31]:
np.random.randint(25)

12

In [34]:
np.random.randint(1,100)

86

In [36]:
np.random.randint(1,100,10)

array([ 1, 77, 27, 19, 71, 64, 34, 94, 25, 40])

In [37]:
np.random.randint(1,100,(2,3))

array([[ 7, 37, 61],
       [61, 42, 69]])

#### shape
- It is a attribute not a method

In [38]:
a=np.arange(25)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [39]:
a.shape

(25,)

#### reshape()

In [40]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [41]:
a.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [43]:
a.reshape(5,-1)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [44]:
b=np.arange(30)
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [45]:
b.shape

(30,)

In [46]:
b.reshape(5,-1)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [47]:
b.reshape(6,-1)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [48]:
b.reshape(10,-1)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29]])

In [49]:
b.reshape(-1,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

#### dtype
- It is a Attribute not a method

In [50]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [51]:
a.dtype

dtype('int32')

#### unique()

In [54]:
l=[1,2,2,2,2,3,3,3,3,4,4,4,5,5,5,6,6,6]
np.unique(l)

array([1, 2, 3, 4, 5, 6])

#### in1d()

In [57]:
l=[1,2,3,4,5]
c=[4,5]
np.in1d(l,c)

array([False, False, False,  True,  True])

#### T or transpose()

In [60]:
a=np.arange(30)

In [61]:
a.reshape(5,-1)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [62]:
a.reshape(5,-1).T

array([[ 0,  6, 12, 18, 24],
       [ 1,  7, 13, 19, 25],
       [ 2,  8, 14, 20, 26],
       [ 3,  9, 15, 21, 27],
       [ 4, 10, 16, 22, 28],
       [ 5, 11, 17, 23, 29]])

In [63]:
a.reshape(5,-1).transpose()

array([[ 0,  6, 12, 18, 24],
       [ 1,  7, 13, 19, 25],
       [ 2,  8, 14, 20, 26],
       [ 3,  9, 15, 21, 27],
       [ 4, 10, 16, 22, 28],
       [ 5, 11, 17, 23, 29]])

#### Universal Array

In [64]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [65]:
np.square(a)

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529, 576, 625,
       676, 729, 784, 841], dtype=int32)

In [66]:
np.sqrt(a)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595, 4.58257569, 4.69041576, 4.79583152, 4.89897949,
       5.        , 5.09901951, 5.19615242, 5.29150262, 5.38516481])

In [67]:
np.sin(a)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111, -0.99999021, -0.53657292,  0.42016704,  0.99060736,
        0.65028784, -0.28790332, -0.96139749, -0.75098725,  0.14987721,
        0.91294525,  0.83665564, -0.00885131, -0.8462204 , -0.90557836,
       -0.13235175,  0.76255845,  0.95637593,  0.27090579, -0.66363388])

In [68]:
np.cos(a)

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362,
        0.28366219,  0.96017029,  0.75390225, -0.14550003, -0.91113026,
       -0.83907153,  0.0044257 ,  0.84385396,  0.90744678,  0.13673722,
       -0.75968791, -0.95765948, -0.27516334,  0.66031671,  0.98870462,
        0.40808206, -0.54772926, -0.99996083, -0.53283302,  0.42417901,
        0.99120281,  0.64691932, -0.29213881, -0.96260587, -0.74805753])

In [69]:
np.mean(a)

14.5

In [70]:
np.std(a)

8.65544144839919

In [71]:
np.var(a)

74.91666666666667

In [72]:
np.log(a)

<ipython-input-72-89b6b8e53c58>:1: RuntimeWarning: divide by zero encountered in log
  np.log(a)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509, 2.39789527, 2.48490665, 2.56494936, 2.63905733,
       2.7080502 , 2.77258872, 2.83321334, 2.89037176, 2.94443898,
       2.99573227, 3.04452244, 3.09104245, 3.13549422, 3.17805383,
       3.21887582, 3.25809654, 3.29583687, 3.33220451, 3.36729583])

In [73]:
np.exp(a)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04,
       1.62754791e+05, 4.42413392e+05, 1.20260428e+06, 3.26901737e+06,
       8.88611052e+06, 2.41549528e+07, 6.56599691e+07, 1.78482301e+08,
       4.85165195e+08, 1.31881573e+09, 3.58491285e+09, 9.74480345e+09,
       2.64891221e+10, 7.20048993e+10, 1.95729609e+11, 5.32048241e+11,
       1.44625706e+12, 3.93133430e+12])

In [75]:
a=12.345
np.round(a,2)

12.34

In [76]:
np.arange(25)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [77]:
np.arange(25,dtype='float')

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24.])

In [78]:
a=np.arange(25)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [79]:
a.max()

24

In [80]:
a.min()

0

In [81]:
a.argmax()

24

In [82]:
a.argmin()

0

#### Indexing and Selection

##### 1-D array

In [88]:
a=np.arange(5)
a

array([0, 1, 2, 3, 4])

In [89]:
#Indexing and Reverse Indexing
print(f'a    :{a}')
print(f'a[0] :{a[0]}')
print(f'a[-1]:{a[-1]}')

a    :[0 1 2 3 4]
a[0] :0
a[-1]:4


In [95]:
#Slicing
print(f'a              :{a}')
print(f'a[0:3]         :{a[0:3]}')
print(f'a[0:{len(a)}:2]:{a[0:len(a):2]}')

a              :[0 1 2 3 4]
a[0:3]         :[0 1 2]
a[0:5:2]:[0 2 4]


In [97]:
print(f'a   :{a}')
print(f'a[:]:{a[:]}')

a   :[0 1 2 3 4]
a[:]:[0 1 2 3 4]


In [98]:
#Reverse a array
print(f' a[::-1]:{a[::-1]}')

 a[::-1]:[4 3 2 1 0]


#### 2-D array

In [100]:
a=np.arange(25)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [101]:
a=a.reshape(5,-1)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [103]:
a[2][2]

12

In [104]:
a[2,2]

12

In [106]:
a[1:3,1:3]

array([[ 6,  7],
       [11, 12]])

In [108]:
a[2:4,2:]

array([[12, 13, 14],
       [17, 18, 19]])

In [112]:
a[2:4,0:2]

array([[10, 11],
       [15, 16]])

#### Broadcasting

In [113]:
#Without Copy
print(f'Without Copy')
a=np.arange(10)
b=a
print(f'a :{a}')
print(f'b :{b}')
print('Change the value in the B array')
b[:]=55
print(f'a :{a}')
print(f'b :{b}')

Without Copy
a :[0 1 2 3 4 5 6 7 8 9]
b :[0 1 2 3 4 5 6 7 8 9]
Change the value in the B array
a :[55 55 55 55 55 55 55 55 55 55]
b :[55 55 55 55 55 55 55 55 55 55]


In [114]:
#With Copy
print(f'With Copy')
a=np.arange(10)
b=a.copy()
print(f'a :{a}')
print(f'b :{b}')
print('Change the value in the B array')
b[:]=55
print(f'a :{a}')
print(f'b :{b}')

With Copy
a :[0 1 2 3 4 5 6 7 8 9]
b :[0 1 2 3 4 5 6 7 8 9]
Change the value in the B array
a :[0 1 2 3 4 5 6 7 8 9]
b :[55 55 55 55 55 55 55 55 55 55]


#### array i/p and o/p

In [129]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [130]:
b=a*3
b

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

#### .npy

In [131]:
#save
np.save('array1',a)

In [132]:
#load
np.load('array1.npy')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### .zip

In [133]:
#save
np.savez('array2',a=a,b=b,c=a**2,d=b**2)

In [134]:
#load
result=np.load('array2.npz')
result['a']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [126]:
result['b']

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [127]:
result['c']

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [128]:
result['d']

array([  0,   9,  36,  81, 144, 225, 324, 441, 576, 729])

#### .txt

In [136]:
#save
np.savetxt('array3',a,delimiter=',')

In [138]:
#load
np.loadtxt('array3',dtype='int')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])